
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Filaments` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Filaments
 * 
 */
export type FilamentsModel = runtime.Types.Result.DefaultSelection<Prisma.$FilamentsPayload>

export type AggregateFilaments = {
  _count: FilamentsCountAggregateOutputType | null
  _avg: FilamentsAvgAggregateOutputType | null
  _sum: FilamentsSumAggregateOutputType | null
  _min: FilamentsMinAggregateOutputType | null
  _max: FilamentsMaxAggregateOutputType | null
}

export type FilamentsAvgAggregateOutputType = {
  id: number | null
  wheight: number | null
  materialId: number | null
}

export type FilamentsSumAggregateOutputType = {
  id: number | null
  wheight: number | null
  materialId: number | null
}

export type FilamentsMinAggregateOutputType = {
  id: number | null
  brand: string | null
  color: string | null
  wheight: number | null
  materialId: number | null
}

export type FilamentsMaxAggregateOutputType = {
  id: number | null
  brand: string | null
  color: string | null
  wheight: number | null
  materialId: number | null
}

export type FilamentsCountAggregateOutputType = {
  id: number
  brand: number
  color: number
  wheight: number
  materialId: number
  _all: number
}


export type FilamentsAvgAggregateInputType = {
  id?: true
  wheight?: true
  materialId?: true
}

export type FilamentsSumAggregateInputType = {
  id?: true
  wheight?: true
  materialId?: true
}

export type FilamentsMinAggregateInputType = {
  id?: true
  brand?: true
  color?: true
  wheight?: true
  materialId?: true
}

export type FilamentsMaxAggregateInputType = {
  id?: true
  brand?: true
  color?: true
  wheight?: true
  materialId?: true
}

export type FilamentsCountAggregateInputType = {
  id?: true
  brand?: true
  color?: true
  wheight?: true
  materialId?: true
  _all?: true
}

export type FilamentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Filaments to aggregate.
   */
  where?: Prisma.FilamentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Filaments to fetch.
   */
  orderBy?: Prisma.FilamentsOrderByWithRelationInput | Prisma.FilamentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FilamentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Filaments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Filaments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Filaments
  **/
  _count?: true | FilamentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FilamentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FilamentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FilamentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FilamentsMaxAggregateInputType
}

export type GetFilamentsAggregateType<T extends FilamentsAggregateArgs> = {
      [P in keyof T & keyof AggregateFilaments]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFilaments[P]>
    : Prisma.GetScalarType<T[P], AggregateFilaments[P]>
}




export type FilamentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FilamentsWhereInput
  orderBy?: Prisma.FilamentsOrderByWithAggregationInput | Prisma.FilamentsOrderByWithAggregationInput[]
  by: Prisma.FilamentsScalarFieldEnum[] | Prisma.FilamentsScalarFieldEnum
  having?: Prisma.FilamentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FilamentsCountAggregateInputType | true
  _avg?: FilamentsAvgAggregateInputType
  _sum?: FilamentsSumAggregateInputType
  _min?: FilamentsMinAggregateInputType
  _max?: FilamentsMaxAggregateInputType
}

export type FilamentsGroupByOutputType = {
  id: number
  brand: string
  color: string
  wheight: number
  materialId: number
  _count: FilamentsCountAggregateOutputType | null
  _avg: FilamentsAvgAggregateOutputType | null
  _sum: FilamentsSumAggregateOutputType | null
  _min: FilamentsMinAggregateOutputType | null
  _max: FilamentsMaxAggregateOutputType | null
}

export type GetFilamentsGroupByPayload<T extends FilamentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FilamentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FilamentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FilamentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FilamentsGroupByOutputType[P]>
      }
    >
  >



export type FilamentsWhereInput = {
  AND?: Prisma.FilamentsWhereInput | Prisma.FilamentsWhereInput[]
  OR?: Prisma.FilamentsWhereInput[]
  NOT?: Prisma.FilamentsWhereInput | Prisma.FilamentsWhereInput[]
  id?: Prisma.IntFilter<"Filaments"> | number
  brand?: Prisma.StringFilter<"Filaments"> | string
  color?: Prisma.StringFilter<"Filaments"> | string
  wheight?: Prisma.FloatFilter<"Filaments"> | number
  materialId?: Prisma.IntFilter<"Filaments"> | number
  material?: Prisma.XOR<Prisma.MaterialsScalarRelationFilter, Prisma.MaterialsWhereInput>
  orders?: Prisma.OrdersListRelationFilter
}

export type FilamentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  color?: Prisma.SortOrder
  wheight?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  material?: Prisma.MaterialsOrderByWithRelationInput
  orders?: Prisma.OrdersOrderByRelationAggregateInput
}

export type FilamentsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.FilamentsWhereInput | Prisma.FilamentsWhereInput[]
  OR?: Prisma.FilamentsWhereInput[]
  NOT?: Prisma.FilamentsWhereInput | Prisma.FilamentsWhereInput[]
  brand?: Prisma.StringFilter<"Filaments"> | string
  color?: Prisma.StringFilter<"Filaments"> | string
  wheight?: Prisma.FloatFilter<"Filaments"> | number
  materialId?: Prisma.IntFilter<"Filaments"> | number
  material?: Prisma.XOR<Prisma.MaterialsScalarRelationFilter, Prisma.MaterialsWhereInput>
  orders?: Prisma.OrdersListRelationFilter
}, "id">

export type FilamentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  color?: Prisma.SortOrder
  wheight?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
  _count?: Prisma.FilamentsCountOrderByAggregateInput
  _avg?: Prisma.FilamentsAvgOrderByAggregateInput
  _max?: Prisma.FilamentsMaxOrderByAggregateInput
  _min?: Prisma.FilamentsMinOrderByAggregateInput
  _sum?: Prisma.FilamentsSumOrderByAggregateInput
}

export type FilamentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.FilamentsScalarWhereWithAggregatesInput | Prisma.FilamentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.FilamentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FilamentsScalarWhereWithAggregatesInput | Prisma.FilamentsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Filaments"> | number
  brand?: Prisma.StringWithAggregatesFilter<"Filaments"> | string
  color?: Prisma.StringWithAggregatesFilter<"Filaments"> | string
  wheight?: Prisma.FloatWithAggregatesFilter<"Filaments"> | number
  materialId?: Prisma.IntWithAggregatesFilter<"Filaments"> | number
}

export type FilamentsCreateInput = {
  brand: string
  color: string
  wheight?: number
  material: Prisma.MaterialsCreateNestedOneWithoutFilamentsInput
  orders?: Prisma.OrdersCreateNestedManyWithoutFilamentsInput
}

export type FilamentsUncheckedCreateInput = {
  id?: number
  brand: string
  color: string
  wheight?: number
  materialId: number
  orders?: Prisma.OrdersUncheckedCreateNestedManyWithoutFilamentsInput
}

export type FilamentsUpdateInput = {
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  wheight?: Prisma.FloatFieldUpdateOperationsInput | number
  material?: Prisma.MaterialsUpdateOneRequiredWithoutFilamentsNestedInput
  orders?: Prisma.OrdersUpdateManyWithoutFilamentsNestedInput
}

export type FilamentsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  wheight?: Prisma.FloatFieldUpdateOperationsInput | number
  materialId?: Prisma.IntFieldUpdateOperationsInput | number
  orders?: Prisma.OrdersUncheckedUpdateManyWithoutFilamentsNestedInput
}

export type FilamentsCreateManyInput = {
  id?: number
  brand: string
  color: string
  wheight?: number
  materialId: number
}

export type FilamentsUpdateManyMutationInput = {
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  wheight?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type FilamentsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  wheight?: Prisma.FloatFieldUpdateOperationsInput | number
  materialId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type FilamentsListRelationFilter = {
  every?: Prisma.FilamentsWhereInput
  some?: Prisma.FilamentsWhereInput
  none?: Prisma.FilamentsWhereInput
}

export type FilamentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FilamentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  color?: Prisma.SortOrder
  wheight?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
}

export type FilamentsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  wheight?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
}

export type FilamentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  color?: Prisma.SortOrder
  wheight?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
}

export type FilamentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  brand?: Prisma.SortOrder
  color?: Prisma.SortOrder
  wheight?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
}

export type FilamentsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  wheight?: Prisma.SortOrder
  materialId?: Prisma.SortOrder
}

export type FilamentsCreateNestedManyWithoutMaterialInput = {
  create?: Prisma.XOR<Prisma.FilamentsCreateWithoutMaterialInput, Prisma.FilamentsUncheckedCreateWithoutMaterialInput> | Prisma.FilamentsCreateWithoutMaterialInput[] | Prisma.FilamentsUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.FilamentsCreateOrConnectWithoutMaterialInput | Prisma.FilamentsCreateOrConnectWithoutMaterialInput[]
  createMany?: Prisma.FilamentsCreateManyMaterialInputEnvelope
  connect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
}

export type FilamentsUncheckedCreateNestedManyWithoutMaterialInput = {
  create?: Prisma.XOR<Prisma.FilamentsCreateWithoutMaterialInput, Prisma.FilamentsUncheckedCreateWithoutMaterialInput> | Prisma.FilamentsCreateWithoutMaterialInput[] | Prisma.FilamentsUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.FilamentsCreateOrConnectWithoutMaterialInput | Prisma.FilamentsCreateOrConnectWithoutMaterialInput[]
  createMany?: Prisma.FilamentsCreateManyMaterialInputEnvelope
  connect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
}

export type FilamentsUpdateManyWithoutMaterialNestedInput = {
  create?: Prisma.XOR<Prisma.FilamentsCreateWithoutMaterialInput, Prisma.FilamentsUncheckedCreateWithoutMaterialInput> | Prisma.FilamentsCreateWithoutMaterialInput[] | Prisma.FilamentsUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.FilamentsCreateOrConnectWithoutMaterialInput | Prisma.FilamentsCreateOrConnectWithoutMaterialInput[]
  upsert?: Prisma.FilamentsUpsertWithWhereUniqueWithoutMaterialInput | Prisma.FilamentsUpsertWithWhereUniqueWithoutMaterialInput[]
  createMany?: Prisma.FilamentsCreateManyMaterialInputEnvelope
  set?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  disconnect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  delete?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  connect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  update?: Prisma.FilamentsUpdateWithWhereUniqueWithoutMaterialInput | Prisma.FilamentsUpdateWithWhereUniqueWithoutMaterialInput[]
  updateMany?: Prisma.FilamentsUpdateManyWithWhereWithoutMaterialInput | Prisma.FilamentsUpdateManyWithWhereWithoutMaterialInput[]
  deleteMany?: Prisma.FilamentsScalarWhereInput | Prisma.FilamentsScalarWhereInput[]
}

export type FilamentsUncheckedUpdateManyWithoutMaterialNestedInput = {
  create?: Prisma.XOR<Prisma.FilamentsCreateWithoutMaterialInput, Prisma.FilamentsUncheckedCreateWithoutMaterialInput> | Prisma.FilamentsCreateWithoutMaterialInput[] | Prisma.FilamentsUncheckedCreateWithoutMaterialInput[]
  connectOrCreate?: Prisma.FilamentsCreateOrConnectWithoutMaterialInput | Prisma.FilamentsCreateOrConnectWithoutMaterialInput[]
  upsert?: Prisma.FilamentsUpsertWithWhereUniqueWithoutMaterialInput | Prisma.FilamentsUpsertWithWhereUniqueWithoutMaterialInput[]
  createMany?: Prisma.FilamentsCreateManyMaterialInputEnvelope
  set?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  disconnect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  delete?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  connect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  update?: Prisma.FilamentsUpdateWithWhereUniqueWithoutMaterialInput | Prisma.FilamentsUpdateWithWhereUniqueWithoutMaterialInput[]
  updateMany?: Prisma.FilamentsUpdateManyWithWhereWithoutMaterialInput | Prisma.FilamentsUpdateManyWithWhereWithoutMaterialInput[]
  deleteMany?: Prisma.FilamentsScalarWhereInput | Prisma.FilamentsScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FilamentsCreateNestedManyWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.FilamentsCreateWithoutOrdersInput, Prisma.FilamentsUncheckedCreateWithoutOrdersInput> | Prisma.FilamentsCreateWithoutOrdersInput[] | Prisma.FilamentsUncheckedCreateWithoutOrdersInput[]
  connectOrCreate?: Prisma.FilamentsCreateOrConnectWithoutOrdersInput | Prisma.FilamentsCreateOrConnectWithoutOrdersInput[]
  connect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
}

export type FilamentsUncheckedCreateNestedManyWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.FilamentsCreateWithoutOrdersInput, Prisma.FilamentsUncheckedCreateWithoutOrdersInput> | Prisma.FilamentsCreateWithoutOrdersInput[] | Prisma.FilamentsUncheckedCreateWithoutOrdersInput[]
  connectOrCreate?: Prisma.FilamentsCreateOrConnectWithoutOrdersInput | Prisma.FilamentsCreateOrConnectWithoutOrdersInput[]
  connect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
}

export type FilamentsUpdateManyWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.FilamentsCreateWithoutOrdersInput, Prisma.FilamentsUncheckedCreateWithoutOrdersInput> | Prisma.FilamentsCreateWithoutOrdersInput[] | Prisma.FilamentsUncheckedCreateWithoutOrdersInput[]
  connectOrCreate?: Prisma.FilamentsCreateOrConnectWithoutOrdersInput | Prisma.FilamentsCreateOrConnectWithoutOrdersInput[]
  upsert?: Prisma.FilamentsUpsertWithWhereUniqueWithoutOrdersInput | Prisma.FilamentsUpsertWithWhereUniqueWithoutOrdersInput[]
  set?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  disconnect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  delete?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  connect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  update?: Prisma.FilamentsUpdateWithWhereUniqueWithoutOrdersInput | Prisma.FilamentsUpdateWithWhereUniqueWithoutOrdersInput[]
  updateMany?: Prisma.FilamentsUpdateManyWithWhereWithoutOrdersInput | Prisma.FilamentsUpdateManyWithWhereWithoutOrdersInput[]
  deleteMany?: Prisma.FilamentsScalarWhereInput | Prisma.FilamentsScalarWhereInput[]
}

export type FilamentsUncheckedUpdateManyWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.FilamentsCreateWithoutOrdersInput, Prisma.FilamentsUncheckedCreateWithoutOrdersInput> | Prisma.FilamentsCreateWithoutOrdersInput[] | Prisma.FilamentsUncheckedCreateWithoutOrdersInput[]
  connectOrCreate?: Prisma.FilamentsCreateOrConnectWithoutOrdersInput | Prisma.FilamentsCreateOrConnectWithoutOrdersInput[]
  upsert?: Prisma.FilamentsUpsertWithWhereUniqueWithoutOrdersInput | Prisma.FilamentsUpsertWithWhereUniqueWithoutOrdersInput[]
  set?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  disconnect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  delete?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  connect?: Prisma.FilamentsWhereUniqueInput | Prisma.FilamentsWhereUniqueInput[]
  update?: Prisma.FilamentsUpdateWithWhereUniqueWithoutOrdersInput | Prisma.FilamentsUpdateWithWhereUniqueWithoutOrdersInput[]
  updateMany?: Prisma.FilamentsUpdateManyWithWhereWithoutOrdersInput | Prisma.FilamentsUpdateManyWithWhereWithoutOrdersInput[]
  deleteMany?: Prisma.FilamentsScalarWhereInput | Prisma.FilamentsScalarWhereInput[]
}

export type FilamentsCreateWithoutMaterialInput = {
  brand: string
  color: string
  wheight?: number
  orders?: Prisma.OrdersCreateNestedManyWithoutFilamentsInput
}

export type FilamentsUncheckedCreateWithoutMaterialInput = {
  id?: number
  brand: string
  color: string
  wheight?: number
  orders?: Prisma.OrdersUncheckedCreateNestedManyWithoutFilamentsInput
}

export type FilamentsCreateOrConnectWithoutMaterialInput = {
  where: Prisma.FilamentsWhereUniqueInput
  create: Prisma.XOR<Prisma.FilamentsCreateWithoutMaterialInput, Prisma.FilamentsUncheckedCreateWithoutMaterialInput>
}

export type FilamentsCreateManyMaterialInputEnvelope = {
  data: Prisma.FilamentsCreateManyMaterialInput | Prisma.FilamentsCreateManyMaterialInput[]
  skipDuplicates?: boolean
}

export type FilamentsUpsertWithWhereUniqueWithoutMaterialInput = {
  where: Prisma.FilamentsWhereUniqueInput
  update: Prisma.XOR<Prisma.FilamentsUpdateWithoutMaterialInput, Prisma.FilamentsUncheckedUpdateWithoutMaterialInput>
  create: Prisma.XOR<Prisma.FilamentsCreateWithoutMaterialInput, Prisma.FilamentsUncheckedCreateWithoutMaterialInput>
}

export type FilamentsUpdateWithWhereUniqueWithoutMaterialInput = {
  where: Prisma.FilamentsWhereUniqueInput
  data: Prisma.XOR<Prisma.FilamentsUpdateWithoutMaterialInput, Prisma.FilamentsUncheckedUpdateWithoutMaterialInput>
}

export type FilamentsUpdateManyWithWhereWithoutMaterialInput = {
  where: Prisma.FilamentsScalarWhereInput
  data: Prisma.XOR<Prisma.FilamentsUpdateManyMutationInput, Prisma.FilamentsUncheckedUpdateManyWithoutMaterialInput>
}

export type FilamentsScalarWhereInput = {
  AND?: Prisma.FilamentsScalarWhereInput | Prisma.FilamentsScalarWhereInput[]
  OR?: Prisma.FilamentsScalarWhereInput[]
  NOT?: Prisma.FilamentsScalarWhereInput | Prisma.FilamentsScalarWhereInput[]
  id?: Prisma.IntFilter<"Filaments"> | number
  brand?: Prisma.StringFilter<"Filaments"> | string
  color?: Prisma.StringFilter<"Filaments"> | string
  wheight?: Prisma.FloatFilter<"Filaments"> | number
  materialId?: Prisma.IntFilter<"Filaments"> | number
}

export type FilamentsCreateWithoutOrdersInput = {
  brand: string
  color: string
  wheight?: number
  material: Prisma.MaterialsCreateNestedOneWithoutFilamentsInput
}

export type FilamentsUncheckedCreateWithoutOrdersInput = {
  id?: number
  brand: string
  color: string
  wheight?: number
  materialId: number
}

export type FilamentsCreateOrConnectWithoutOrdersInput = {
  where: Prisma.FilamentsWhereUniqueInput
  create: Prisma.XOR<Prisma.FilamentsCreateWithoutOrdersInput, Prisma.FilamentsUncheckedCreateWithoutOrdersInput>
}

export type FilamentsUpsertWithWhereUniqueWithoutOrdersInput = {
  where: Prisma.FilamentsWhereUniqueInput
  update: Prisma.XOR<Prisma.FilamentsUpdateWithoutOrdersInput, Prisma.FilamentsUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.FilamentsCreateWithoutOrdersInput, Prisma.FilamentsUncheckedCreateWithoutOrdersInput>
}

export type FilamentsUpdateWithWhereUniqueWithoutOrdersInput = {
  where: Prisma.FilamentsWhereUniqueInput
  data: Prisma.XOR<Prisma.FilamentsUpdateWithoutOrdersInput, Prisma.FilamentsUncheckedUpdateWithoutOrdersInput>
}

export type FilamentsUpdateManyWithWhereWithoutOrdersInput = {
  where: Prisma.FilamentsScalarWhereInput
  data: Prisma.XOR<Prisma.FilamentsUpdateManyMutationInput, Prisma.FilamentsUncheckedUpdateManyWithoutOrdersInput>
}

export type FilamentsCreateManyMaterialInput = {
  id?: number
  brand: string
  color: string
  wheight?: number
}

export type FilamentsUpdateWithoutMaterialInput = {
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  wheight?: Prisma.FloatFieldUpdateOperationsInput | number
  orders?: Prisma.OrdersUpdateManyWithoutFilamentsNestedInput
}

export type FilamentsUncheckedUpdateWithoutMaterialInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  wheight?: Prisma.FloatFieldUpdateOperationsInput | number
  orders?: Prisma.OrdersUncheckedUpdateManyWithoutFilamentsNestedInput
}

export type FilamentsUncheckedUpdateManyWithoutMaterialInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  wheight?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type FilamentsUpdateWithoutOrdersInput = {
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  wheight?: Prisma.FloatFieldUpdateOperationsInput | number
  material?: Prisma.MaterialsUpdateOneRequiredWithoutFilamentsNestedInput
}

export type FilamentsUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  wheight?: Prisma.FloatFieldUpdateOperationsInput | number
  materialId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type FilamentsUncheckedUpdateManyWithoutOrdersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  brand?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  wheight?: Prisma.FloatFieldUpdateOperationsInput | number
  materialId?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type FilamentsCountOutputType
 */

export type FilamentsCountOutputType = {
  orders: number
}

export type FilamentsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  orders?: boolean | FilamentsCountOutputTypeCountOrdersArgs
}

/**
 * FilamentsCountOutputType without action
 */
export type FilamentsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilamentsCountOutputType
   */
  select?: Prisma.FilamentsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FilamentsCountOutputType without action
 */
export type FilamentsCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrdersWhereInput
}


export type FilamentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  brand?: boolean
  color?: boolean
  wheight?: boolean
  materialId?: boolean
  material?: boolean | Prisma.MaterialsDefaultArgs<ExtArgs>
  orders?: boolean | Prisma.Filaments$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.FilamentsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["filaments"]>

export type FilamentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  brand?: boolean
  color?: boolean
  wheight?: boolean
  materialId?: boolean
  material?: boolean | Prisma.MaterialsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["filaments"]>

export type FilamentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  brand?: boolean
  color?: boolean
  wheight?: boolean
  materialId?: boolean
  material?: boolean | Prisma.MaterialsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["filaments"]>

export type FilamentsSelectScalar = {
  id?: boolean
  brand?: boolean
  color?: boolean
  wheight?: boolean
  materialId?: boolean
}

export type FilamentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "brand" | "color" | "wheight" | "materialId", ExtArgs["result"]["filaments"]>
export type FilamentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  material?: boolean | Prisma.MaterialsDefaultArgs<ExtArgs>
  orders?: boolean | Prisma.Filaments$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.FilamentsCountOutputTypeDefaultArgs<ExtArgs>
}
export type FilamentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  material?: boolean | Prisma.MaterialsDefaultArgs<ExtArgs>
}
export type FilamentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  material?: boolean | Prisma.MaterialsDefaultArgs<ExtArgs>
}

export type $FilamentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Filaments"
  objects: {
    material: Prisma.$MaterialsPayload<ExtArgs>
    orders: Prisma.$OrdersPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    brand: string
    color: string
    wheight: number
    materialId: number
  }, ExtArgs["result"]["filaments"]>
  composites: {}
}

export type FilamentsGetPayload<S extends boolean | null | undefined | FilamentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FilamentsPayload, S>

export type FilamentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FilamentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FilamentsCountAggregateInputType | true
  }

export interface FilamentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Filaments'], meta: { name: 'Filaments' } }
  /**
   * Find zero or one Filaments that matches the filter.
   * @param {FilamentsFindUniqueArgs} args - Arguments to find a Filaments
   * @example
   * // Get one Filaments
   * const filaments = await prisma.filaments.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FilamentsFindUniqueArgs>(args: Prisma.SelectSubset<T, FilamentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FilamentsClient<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Filaments that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FilamentsFindUniqueOrThrowArgs} args - Arguments to find a Filaments
   * @example
   * // Get one Filaments
   * const filaments = await prisma.filaments.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FilamentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FilamentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilamentsClient<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Filaments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilamentsFindFirstArgs} args - Arguments to find a Filaments
   * @example
   * // Get one Filaments
   * const filaments = await prisma.filaments.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FilamentsFindFirstArgs>(args?: Prisma.SelectSubset<T, FilamentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__FilamentsClient<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Filaments that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilamentsFindFirstOrThrowArgs} args - Arguments to find a Filaments
   * @example
   * // Get one Filaments
   * const filaments = await prisma.filaments.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FilamentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FilamentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilamentsClient<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Filaments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilamentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Filaments
   * const filaments = await prisma.filaments.findMany()
   * 
   * // Get first 10 Filaments
   * const filaments = await prisma.filaments.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const filamentsWithIdOnly = await prisma.filaments.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FilamentsFindManyArgs>(args?: Prisma.SelectSubset<T, FilamentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Filaments.
   * @param {FilamentsCreateArgs} args - Arguments to create a Filaments.
   * @example
   * // Create one Filaments
   * const Filaments = await prisma.filaments.create({
   *   data: {
   *     // ... data to create a Filaments
   *   }
   * })
   * 
   */
  create<T extends FilamentsCreateArgs>(args: Prisma.SelectSubset<T, FilamentsCreateArgs<ExtArgs>>): Prisma.Prisma__FilamentsClient<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Filaments.
   * @param {FilamentsCreateManyArgs} args - Arguments to create many Filaments.
   * @example
   * // Create many Filaments
   * const filaments = await prisma.filaments.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FilamentsCreateManyArgs>(args?: Prisma.SelectSubset<T, FilamentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Filaments and returns the data saved in the database.
   * @param {FilamentsCreateManyAndReturnArgs} args - Arguments to create many Filaments.
   * @example
   * // Create many Filaments
   * const filaments = await prisma.filaments.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Filaments and only return the `id`
   * const filamentsWithIdOnly = await prisma.filaments.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FilamentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FilamentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Filaments.
   * @param {FilamentsDeleteArgs} args - Arguments to delete one Filaments.
   * @example
   * // Delete one Filaments
   * const Filaments = await prisma.filaments.delete({
   *   where: {
   *     // ... filter to delete one Filaments
   *   }
   * })
   * 
   */
  delete<T extends FilamentsDeleteArgs>(args: Prisma.SelectSubset<T, FilamentsDeleteArgs<ExtArgs>>): Prisma.Prisma__FilamentsClient<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Filaments.
   * @param {FilamentsUpdateArgs} args - Arguments to update one Filaments.
   * @example
   * // Update one Filaments
   * const filaments = await prisma.filaments.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FilamentsUpdateArgs>(args: Prisma.SelectSubset<T, FilamentsUpdateArgs<ExtArgs>>): Prisma.Prisma__FilamentsClient<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Filaments.
   * @param {FilamentsDeleteManyArgs} args - Arguments to filter Filaments to delete.
   * @example
   * // Delete a few Filaments
   * const { count } = await prisma.filaments.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FilamentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, FilamentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Filaments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilamentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Filaments
   * const filaments = await prisma.filaments.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FilamentsUpdateManyArgs>(args: Prisma.SelectSubset<T, FilamentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Filaments and returns the data updated in the database.
   * @param {FilamentsUpdateManyAndReturnArgs} args - Arguments to update many Filaments.
   * @example
   * // Update many Filaments
   * const filaments = await prisma.filaments.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Filaments and only return the `id`
   * const filamentsWithIdOnly = await prisma.filaments.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FilamentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FilamentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Filaments.
   * @param {FilamentsUpsertArgs} args - Arguments to update or create a Filaments.
   * @example
   * // Update or create a Filaments
   * const filaments = await prisma.filaments.upsert({
   *   create: {
   *     // ... data to create a Filaments
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Filaments we want to update
   *   }
   * })
   */
  upsert<T extends FilamentsUpsertArgs>(args: Prisma.SelectSubset<T, FilamentsUpsertArgs<ExtArgs>>): Prisma.Prisma__FilamentsClient<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Filaments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilamentsCountArgs} args - Arguments to filter Filaments to count.
   * @example
   * // Count the number of Filaments
   * const count = await prisma.filaments.count({
   *   where: {
   *     // ... the filter for the Filaments we want to count
   *   }
   * })
  **/
  count<T extends FilamentsCountArgs>(
    args?: Prisma.Subset<T, FilamentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FilamentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Filaments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilamentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FilamentsAggregateArgs>(args: Prisma.Subset<T, FilamentsAggregateArgs>): Prisma.PrismaPromise<GetFilamentsAggregateType<T>>

  /**
   * Group by Filaments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilamentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FilamentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FilamentsGroupByArgs['orderBy'] }
      : { orderBy?: FilamentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FilamentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFilamentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Filaments model
 */
readonly fields: FilamentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Filaments.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FilamentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  material<T extends Prisma.MaterialsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MaterialsDefaultArgs<ExtArgs>>): Prisma.Prisma__MaterialsClient<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  orders<T extends Prisma.Filaments$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Filaments$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrdersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Filaments model
 */
export interface FilamentsFieldRefs {
  readonly id: Prisma.FieldRef<"Filaments", 'Int'>
  readonly brand: Prisma.FieldRef<"Filaments", 'String'>
  readonly color: Prisma.FieldRef<"Filaments", 'String'>
  readonly wheight: Prisma.FieldRef<"Filaments", 'Float'>
  readonly materialId: Prisma.FieldRef<"Filaments", 'Int'>
}
    

// Custom InputTypes
/**
 * Filaments findUnique
 */
export type FilamentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
  /**
   * Filter, which Filaments to fetch.
   */
  where: Prisma.FilamentsWhereUniqueInput
}

/**
 * Filaments findUniqueOrThrow
 */
export type FilamentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
  /**
   * Filter, which Filaments to fetch.
   */
  where: Prisma.FilamentsWhereUniqueInput
}

/**
 * Filaments findFirst
 */
export type FilamentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
  /**
   * Filter, which Filaments to fetch.
   */
  where?: Prisma.FilamentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Filaments to fetch.
   */
  orderBy?: Prisma.FilamentsOrderByWithRelationInput | Prisma.FilamentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Filaments.
   */
  cursor?: Prisma.FilamentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Filaments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Filaments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Filaments.
   */
  distinct?: Prisma.FilamentsScalarFieldEnum | Prisma.FilamentsScalarFieldEnum[]
}

/**
 * Filaments findFirstOrThrow
 */
export type FilamentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
  /**
   * Filter, which Filaments to fetch.
   */
  where?: Prisma.FilamentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Filaments to fetch.
   */
  orderBy?: Prisma.FilamentsOrderByWithRelationInput | Prisma.FilamentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Filaments.
   */
  cursor?: Prisma.FilamentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Filaments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Filaments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Filaments.
   */
  distinct?: Prisma.FilamentsScalarFieldEnum | Prisma.FilamentsScalarFieldEnum[]
}

/**
 * Filaments findMany
 */
export type FilamentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
  /**
   * Filter, which Filaments to fetch.
   */
  where?: Prisma.FilamentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Filaments to fetch.
   */
  orderBy?: Prisma.FilamentsOrderByWithRelationInput | Prisma.FilamentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Filaments.
   */
  cursor?: Prisma.FilamentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Filaments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Filaments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Filaments.
   */
  distinct?: Prisma.FilamentsScalarFieldEnum | Prisma.FilamentsScalarFieldEnum[]
}

/**
 * Filaments create
 */
export type FilamentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
  /**
   * The data needed to create a Filaments.
   */
  data: Prisma.XOR<Prisma.FilamentsCreateInput, Prisma.FilamentsUncheckedCreateInput>
}

/**
 * Filaments createMany
 */
export type FilamentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Filaments.
   */
  data: Prisma.FilamentsCreateManyInput | Prisma.FilamentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Filaments createManyAndReturn
 */
export type FilamentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * The data used to create many Filaments.
   */
  data: Prisma.FilamentsCreateManyInput | Prisma.FilamentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Filaments update
 */
export type FilamentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
  /**
   * The data needed to update a Filaments.
   */
  data: Prisma.XOR<Prisma.FilamentsUpdateInput, Prisma.FilamentsUncheckedUpdateInput>
  /**
   * Choose, which Filaments to update.
   */
  where: Prisma.FilamentsWhereUniqueInput
}

/**
 * Filaments updateMany
 */
export type FilamentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Filaments.
   */
  data: Prisma.XOR<Prisma.FilamentsUpdateManyMutationInput, Prisma.FilamentsUncheckedUpdateManyInput>
  /**
   * Filter which Filaments to update
   */
  where?: Prisma.FilamentsWhereInput
  /**
   * Limit how many Filaments to update.
   */
  limit?: number
}

/**
 * Filaments updateManyAndReturn
 */
export type FilamentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * The data used to update Filaments.
   */
  data: Prisma.XOR<Prisma.FilamentsUpdateManyMutationInput, Prisma.FilamentsUncheckedUpdateManyInput>
  /**
   * Filter which Filaments to update
   */
  where?: Prisma.FilamentsWhereInput
  /**
   * Limit how many Filaments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Filaments upsert
 */
export type FilamentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
  /**
   * The filter to search for the Filaments to update in case it exists.
   */
  where: Prisma.FilamentsWhereUniqueInput
  /**
   * In case the Filaments found by the `where` argument doesn't exist, create a new Filaments with this data.
   */
  create: Prisma.XOR<Prisma.FilamentsCreateInput, Prisma.FilamentsUncheckedCreateInput>
  /**
   * In case the Filaments was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FilamentsUpdateInput, Prisma.FilamentsUncheckedUpdateInput>
}

/**
 * Filaments delete
 */
export type FilamentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
  /**
   * Filter which Filaments to delete.
   */
  where: Prisma.FilamentsWhereUniqueInput
}

/**
 * Filaments deleteMany
 */
export type FilamentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Filaments to delete
   */
  where?: Prisma.FilamentsWhereInput
  /**
   * Limit how many Filaments to delete.
   */
  limit?: number
}

/**
 * Filaments.orders
 */
export type Filaments$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Orders
   */
  select?: Prisma.OrdersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Orders
   */
  omit?: Prisma.OrdersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdersInclude<ExtArgs> | null
  where?: Prisma.OrdersWhereInput
  orderBy?: Prisma.OrdersOrderByWithRelationInput | Prisma.OrdersOrderByWithRelationInput[]
  cursor?: Prisma.OrdersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrdersScalarFieldEnum | Prisma.OrdersScalarFieldEnum[]
}

/**
 * Filaments without action
 */
export type FilamentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
}
