
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Materials` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Materials
 * 
 */
export type MaterialsModel = runtime.Types.Result.DefaultSelection<Prisma.$MaterialsPayload>

export type AggregateMaterials = {
  _count: MaterialsCountAggregateOutputType | null
  _avg: MaterialsAvgAggregateOutputType | null
  _sum: MaterialsSumAggregateOutputType | null
  _min: MaterialsMinAggregateOutputType | null
  _max: MaterialsMaxAggregateOutputType | null
}

export type MaterialsAvgAggregateOutputType = {
  id: number | null
}

export type MaterialsSumAggregateOutputType = {
  id: number | null
}

export type MaterialsMinAggregateOutputType = {
  id: number | null
  name: string | null
}

export type MaterialsMaxAggregateOutputType = {
  id: number | null
  name: string | null
}

export type MaterialsCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type MaterialsAvgAggregateInputType = {
  id?: true
}

export type MaterialsSumAggregateInputType = {
  id?: true
}

export type MaterialsMinAggregateInputType = {
  id?: true
  name?: true
}

export type MaterialsMaxAggregateInputType = {
  id?: true
  name?: true
}

export type MaterialsCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type MaterialsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Materials to aggregate.
   */
  where?: Prisma.MaterialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Materials to fetch.
   */
  orderBy?: Prisma.MaterialsOrderByWithRelationInput | Prisma.MaterialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MaterialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Materials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Materials
  **/
  _count?: true | MaterialsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MaterialsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MaterialsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MaterialsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MaterialsMaxAggregateInputType
}

export type GetMaterialsAggregateType<T extends MaterialsAggregateArgs> = {
      [P in keyof T & keyof AggregateMaterials]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMaterials[P]>
    : Prisma.GetScalarType<T[P], AggregateMaterials[P]>
}




export type MaterialsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaterialsWhereInput
  orderBy?: Prisma.MaterialsOrderByWithAggregationInput | Prisma.MaterialsOrderByWithAggregationInput[]
  by: Prisma.MaterialsScalarFieldEnum[] | Prisma.MaterialsScalarFieldEnum
  having?: Prisma.MaterialsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MaterialsCountAggregateInputType | true
  _avg?: MaterialsAvgAggregateInputType
  _sum?: MaterialsSumAggregateInputType
  _min?: MaterialsMinAggregateInputType
  _max?: MaterialsMaxAggregateInputType
}

export type MaterialsGroupByOutputType = {
  id: number
  name: string
  _count: MaterialsCountAggregateOutputType | null
  _avg: MaterialsAvgAggregateOutputType | null
  _sum: MaterialsSumAggregateOutputType | null
  _min: MaterialsMinAggregateOutputType | null
  _max: MaterialsMaxAggregateOutputType | null
}

export type GetMaterialsGroupByPayload<T extends MaterialsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MaterialsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MaterialsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MaterialsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MaterialsGroupByOutputType[P]>
      }
    >
  >



export type MaterialsWhereInput = {
  AND?: Prisma.MaterialsWhereInput | Prisma.MaterialsWhereInput[]
  OR?: Prisma.MaterialsWhereInput[]
  NOT?: Prisma.MaterialsWhereInput | Prisma.MaterialsWhereInput[]
  id?: Prisma.IntFilter<"Materials"> | number
  name?: Prisma.StringFilter<"Materials"> | string
  filaments?: Prisma.FilamentsListRelationFilter
}

export type MaterialsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  filaments?: Prisma.FilamentsOrderByRelationAggregateInput
}

export type MaterialsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MaterialsWhereInput | Prisma.MaterialsWhereInput[]
  OR?: Prisma.MaterialsWhereInput[]
  NOT?: Prisma.MaterialsWhereInput | Prisma.MaterialsWhereInput[]
  name?: Prisma.StringFilter<"Materials"> | string
  filaments?: Prisma.FilamentsListRelationFilter
}, "id">

export type MaterialsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.MaterialsCountOrderByAggregateInput
  _avg?: Prisma.MaterialsAvgOrderByAggregateInput
  _max?: Prisma.MaterialsMaxOrderByAggregateInput
  _min?: Prisma.MaterialsMinOrderByAggregateInput
  _sum?: Prisma.MaterialsSumOrderByAggregateInput
}

export type MaterialsScalarWhereWithAggregatesInput = {
  AND?: Prisma.MaterialsScalarWhereWithAggregatesInput | Prisma.MaterialsScalarWhereWithAggregatesInput[]
  OR?: Prisma.MaterialsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MaterialsScalarWhereWithAggregatesInput | Prisma.MaterialsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Materials"> | number
  name?: Prisma.StringWithAggregatesFilter<"Materials"> | string
}

export type MaterialsCreateInput = {
  name: string
  filaments?: Prisma.FilamentsCreateNestedManyWithoutMaterialInput
}

export type MaterialsUncheckedCreateInput = {
  id?: number
  name: string
  filaments?: Prisma.FilamentsUncheckedCreateNestedManyWithoutMaterialInput
}

export type MaterialsUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  filaments?: Prisma.FilamentsUpdateManyWithoutMaterialNestedInput
}

export type MaterialsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  filaments?: Prisma.FilamentsUncheckedUpdateManyWithoutMaterialNestedInput
}

export type MaterialsCreateManyInput = {
  id?: number
  name: string
}

export type MaterialsUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MaterialsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MaterialsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type MaterialsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MaterialsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type MaterialsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type MaterialsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type MaterialsScalarRelationFilter = {
  is?: Prisma.MaterialsWhereInput
  isNot?: Prisma.MaterialsWhereInput
}

export type MaterialsCreateNestedOneWithoutFilamentsInput = {
  create?: Prisma.XOR<Prisma.MaterialsCreateWithoutFilamentsInput, Prisma.MaterialsUncheckedCreateWithoutFilamentsInput>
  connectOrCreate?: Prisma.MaterialsCreateOrConnectWithoutFilamentsInput
  connect?: Prisma.MaterialsWhereUniqueInput
}

export type MaterialsUpdateOneRequiredWithoutFilamentsNestedInput = {
  create?: Prisma.XOR<Prisma.MaterialsCreateWithoutFilamentsInput, Prisma.MaterialsUncheckedCreateWithoutFilamentsInput>
  connectOrCreate?: Prisma.MaterialsCreateOrConnectWithoutFilamentsInput
  upsert?: Prisma.MaterialsUpsertWithoutFilamentsInput
  connect?: Prisma.MaterialsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MaterialsUpdateToOneWithWhereWithoutFilamentsInput, Prisma.MaterialsUpdateWithoutFilamentsInput>, Prisma.MaterialsUncheckedUpdateWithoutFilamentsInput>
}

export type MaterialsCreateWithoutFilamentsInput = {
  name: string
}

export type MaterialsUncheckedCreateWithoutFilamentsInput = {
  id?: number
  name: string
}

export type MaterialsCreateOrConnectWithoutFilamentsInput = {
  where: Prisma.MaterialsWhereUniqueInput
  create: Prisma.XOR<Prisma.MaterialsCreateWithoutFilamentsInput, Prisma.MaterialsUncheckedCreateWithoutFilamentsInput>
}

export type MaterialsUpsertWithoutFilamentsInput = {
  update: Prisma.XOR<Prisma.MaterialsUpdateWithoutFilamentsInput, Prisma.MaterialsUncheckedUpdateWithoutFilamentsInput>
  create: Prisma.XOR<Prisma.MaterialsCreateWithoutFilamentsInput, Prisma.MaterialsUncheckedCreateWithoutFilamentsInput>
  where?: Prisma.MaterialsWhereInput
}

export type MaterialsUpdateToOneWithWhereWithoutFilamentsInput = {
  where?: Prisma.MaterialsWhereInput
  data: Prisma.XOR<Prisma.MaterialsUpdateWithoutFilamentsInput, Prisma.MaterialsUncheckedUpdateWithoutFilamentsInput>
}

export type MaterialsUpdateWithoutFilamentsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MaterialsUncheckedUpdateWithoutFilamentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type MaterialsCountOutputType
 */

export type MaterialsCountOutputType = {
  filaments: number
}

export type MaterialsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filaments?: boolean | MaterialsCountOutputTypeCountFilamentsArgs
}

/**
 * MaterialsCountOutputType without action
 */
export type MaterialsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaterialsCountOutputType
   */
  select?: Prisma.MaterialsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MaterialsCountOutputType without action
 */
export type MaterialsCountOutputTypeCountFilamentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FilamentsWhereInput
}


export type MaterialsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  filaments?: boolean | Prisma.Materials$filamentsArgs<ExtArgs>
  _count?: boolean | Prisma.MaterialsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["materials"]>

export type MaterialsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["materials"]>

export type MaterialsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["materials"]>

export type MaterialsSelectScalar = {
  id?: boolean
  name?: boolean
}

export type MaterialsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["materials"]>
export type MaterialsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filaments?: boolean | Prisma.Materials$filamentsArgs<ExtArgs>
  _count?: boolean | Prisma.MaterialsCountOutputTypeDefaultArgs<ExtArgs>
}
export type MaterialsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type MaterialsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $MaterialsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Materials"
  objects: {
    filaments: Prisma.$FilamentsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
  }, ExtArgs["result"]["materials"]>
  composites: {}
}

export type MaterialsGetPayload<S extends boolean | null | undefined | MaterialsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MaterialsPayload, S>

export type MaterialsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MaterialsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MaterialsCountAggregateInputType | true
  }

export interface MaterialsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Materials'], meta: { name: 'Materials' } }
  /**
   * Find zero or one Materials that matches the filter.
   * @param {MaterialsFindUniqueArgs} args - Arguments to find a Materials
   * @example
   * // Get one Materials
   * const materials = await prisma.materials.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MaterialsFindUniqueArgs>(args: Prisma.SelectSubset<T, MaterialsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MaterialsClient<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Materials that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MaterialsFindUniqueOrThrowArgs} args - Arguments to find a Materials
   * @example
   * // Get one Materials
   * const materials = await prisma.materials.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MaterialsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MaterialsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaterialsClient<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Materials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsFindFirstArgs} args - Arguments to find a Materials
   * @example
   * // Get one Materials
   * const materials = await prisma.materials.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MaterialsFindFirstArgs>(args?: Prisma.SelectSubset<T, MaterialsFindFirstArgs<ExtArgs>>): Prisma.Prisma__MaterialsClient<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Materials that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsFindFirstOrThrowArgs} args - Arguments to find a Materials
   * @example
   * // Get one Materials
   * const materials = await prisma.materials.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MaterialsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MaterialsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaterialsClient<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Materials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Materials
   * const materials = await prisma.materials.findMany()
   * 
   * // Get first 10 Materials
   * const materials = await prisma.materials.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const materialsWithIdOnly = await prisma.materials.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MaterialsFindManyArgs>(args?: Prisma.SelectSubset<T, MaterialsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Materials.
   * @param {MaterialsCreateArgs} args - Arguments to create a Materials.
   * @example
   * // Create one Materials
   * const Materials = await prisma.materials.create({
   *   data: {
   *     // ... data to create a Materials
   *   }
   * })
   * 
   */
  create<T extends MaterialsCreateArgs>(args: Prisma.SelectSubset<T, MaterialsCreateArgs<ExtArgs>>): Prisma.Prisma__MaterialsClient<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Materials.
   * @param {MaterialsCreateManyArgs} args - Arguments to create many Materials.
   * @example
   * // Create many Materials
   * const materials = await prisma.materials.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MaterialsCreateManyArgs>(args?: Prisma.SelectSubset<T, MaterialsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Materials and returns the data saved in the database.
   * @param {MaterialsCreateManyAndReturnArgs} args - Arguments to create many Materials.
   * @example
   * // Create many Materials
   * const materials = await prisma.materials.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Materials and only return the `id`
   * const materialsWithIdOnly = await prisma.materials.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MaterialsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MaterialsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Materials.
   * @param {MaterialsDeleteArgs} args - Arguments to delete one Materials.
   * @example
   * // Delete one Materials
   * const Materials = await prisma.materials.delete({
   *   where: {
   *     // ... filter to delete one Materials
   *   }
   * })
   * 
   */
  delete<T extends MaterialsDeleteArgs>(args: Prisma.SelectSubset<T, MaterialsDeleteArgs<ExtArgs>>): Prisma.Prisma__MaterialsClient<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Materials.
   * @param {MaterialsUpdateArgs} args - Arguments to update one Materials.
   * @example
   * // Update one Materials
   * const materials = await prisma.materials.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MaterialsUpdateArgs>(args: Prisma.SelectSubset<T, MaterialsUpdateArgs<ExtArgs>>): Prisma.Prisma__MaterialsClient<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Materials.
   * @param {MaterialsDeleteManyArgs} args - Arguments to filter Materials to delete.
   * @example
   * // Delete a few Materials
   * const { count } = await prisma.materials.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MaterialsDeleteManyArgs>(args?: Prisma.SelectSubset<T, MaterialsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Materials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Materials
   * const materials = await prisma.materials.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MaterialsUpdateManyArgs>(args: Prisma.SelectSubset<T, MaterialsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Materials and returns the data updated in the database.
   * @param {MaterialsUpdateManyAndReturnArgs} args - Arguments to update many Materials.
   * @example
   * // Update many Materials
   * const materials = await prisma.materials.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Materials and only return the `id`
   * const materialsWithIdOnly = await prisma.materials.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MaterialsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MaterialsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Materials.
   * @param {MaterialsUpsertArgs} args - Arguments to update or create a Materials.
   * @example
   * // Update or create a Materials
   * const materials = await prisma.materials.upsert({
   *   create: {
   *     // ... data to create a Materials
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Materials we want to update
   *   }
   * })
   */
  upsert<T extends MaterialsUpsertArgs>(args: Prisma.SelectSubset<T, MaterialsUpsertArgs<ExtArgs>>): Prisma.Prisma__MaterialsClient<runtime.Types.Result.GetResult<Prisma.$MaterialsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Materials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsCountArgs} args - Arguments to filter Materials to count.
   * @example
   * // Count the number of Materials
   * const count = await prisma.materials.count({
   *   where: {
   *     // ... the filter for the Materials we want to count
   *   }
   * })
  **/
  count<T extends MaterialsCountArgs>(
    args?: Prisma.Subset<T, MaterialsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MaterialsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Materials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MaterialsAggregateArgs>(args: Prisma.Subset<T, MaterialsAggregateArgs>): Prisma.PrismaPromise<GetMaterialsAggregateType<T>>

  /**
   * Group by Materials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaterialsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MaterialsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MaterialsGroupByArgs['orderBy'] }
      : { orderBy?: MaterialsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MaterialsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMaterialsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Materials model
 */
readonly fields: MaterialsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Materials.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MaterialsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  filaments<T extends Prisma.Materials$filamentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Materials$filamentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilamentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Materials model
 */
export interface MaterialsFieldRefs {
  readonly id: Prisma.FieldRef<"Materials", 'Int'>
  readonly name: Prisma.FieldRef<"Materials", 'String'>
}
    

// Custom InputTypes
/**
 * Materials findUnique
 */
export type MaterialsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInclude<ExtArgs> | null
  /**
   * Filter, which Materials to fetch.
   */
  where: Prisma.MaterialsWhereUniqueInput
}

/**
 * Materials findUniqueOrThrow
 */
export type MaterialsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInclude<ExtArgs> | null
  /**
   * Filter, which Materials to fetch.
   */
  where: Prisma.MaterialsWhereUniqueInput
}

/**
 * Materials findFirst
 */
export type MaterialsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInclude<ExtArgs> | null
  /**
   * Filter, which Materials to fetch.
   */
  where?: Prisma.MaterialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Materials to fetch.
   */
  orderBy?: Prisma.MaterialsOrderByWithRelationInput | Prisma.MaterialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Materials.
   */
  cursor?: Prisma.MaterialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Materials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Materials.
   */
  distinct?: Prisma.MaterialsScalarFieldEnum | Prisma.MaterialsScalarFieldEnum[]
}

/**
 * Materials findFirstOrThrow
 */
export type MaterialsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInclude<ExtArgs> | null
  /**
   * Filter, which Materials to fetch.
   */
  where?: Prisma.MaterialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Materials to fetch.
   */
  orderBy?: Prisma.MaterialsOrderByWithRelationInput | Prisma.MaterialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Materials.
   */
  cursor?: Prisma.MaterialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Materials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Materials.
   */
  distinct?: Prisma.MaterialsScalarFieldEnum | Prisma.MaterialsScalarFieldEnum[]
}

/**
 * Materials findMany
 */
export type MaterialsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInclude<ExtArgs> | null
  /**
   * Filter, which Materials to fetch.
   */
  where?: Prisma.MaterialsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Materials to fetch.
   */
  orderBy?: Prisma.MaterialsOrderByWithRelationInput | Prisma.MaterialsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Materials.
   */
  cursor?: Prisma.MaterialsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Materials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Materials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Materials.
   */
  distinct?: Prisma.MaterialsScalarFieldEnum | Prisma.MaterialsScalarFieldEnum[]
}

/**
 * Materials create
 */
export type MaterialsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInclude<ExtArgs> | null
  /**
   * The data needed to create a Materials.
   */
  data: Prisma.XOR<Prisma.MaterialsCreateInput, Prisma.MaterialsUncheckedCreateInput>
}

/**
 * Materials createMany
 */
export type MaterialsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Materials.
   */
  data: Prisma.MaterialsCreateManyInput | Prisma.MaterialsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Materials createManyAndReturn
 */
export type MaterialsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * The data used to create many Materials.
   */
  data: Prisma.MaterialsCreateManyInput | Prisma.MaterialsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Materials update
 */
export type MaterialsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInclude<ExtArgs> | null
  /**
   * The data needed to update a Materials.
   */
  data: Prisma.XOR<Prisma.MaterialsUpdateInput, Prisma.MaterialsUncheckedUpdateInput>
  /**
   * Choose, which Materials to update.
   */
  where: Prisma.MaterialsWhereUniqueInput
}

/**
 * Materials updateMany
 */
export type MaterialsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Materials.
   */
  data: Prisma.XOR<Prisma.MaterialsUpdateManyMutationInput, Prisma.MaterialsUncheckedUpdateManyInput>
  /**
   * Filter which Materials to update
   */
  where?: Prisma.MaterialsWhereInput
  /**
   * Limit how many Materials to update.
   */
  limit?: number
}

/**
 * Materials updateManyAndReturn
 */
export type MaterialsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * The data used to update Materials.
   */
  data: Prisma.XOR<Prisma.MaterialsUpdateManyMutationInput, Prisma.MaterialsUncheckedUpdateManyInput>
  /**
   * Filter which Materials to update
   */
  where?: Prisma.MaterialsWhereInput
  /**
   * Limit how many Materials to update.
   */
  limit?: number
}

/**
 * Materials upsert
 */
export type MaterialsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInclude<ExtArgs> | null
  /**
   * The filter to search for the Materials to update in case it exists.
   */
  where: Prisma.MaterialsWhereUniqueInput
  /**
   * In case the Materials found by the `where` argument doesn't exist, create a new Materials with this data.
   */
  create: Prisma.XOR<Prisma.MaterialsCreateInput, Prisma.MaterialsUncheckedCreateInput>
  /**
   * In case the Materials was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MaterialsUpdateInput, Prisma.MaterialsUncheckedUpdateInput>
}

/**
 * Materials delete
 */
export type MaterialsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInclude<ExtArgs> | null
  /**
   * Filter which Materials to delete.
   */
  where: Prisma.MaterialsWhereUniqueInput
}

/**
 * Materials deleteMany
 */
export type MaterialsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Materials to delete
   */
  where?: Prisma.MaterialsWhereInput
  /**
   * Limit how many Materials to delete.
   */
  limit?: number
}

/**
 * Materials.filaments
 */
export type Materials$filamentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filaments
   */
  select?: Prisma.FilamentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filaments
   */
  omit?: Prisma.FilamentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilamentsInclude<ExtArgs> | null
  where?: Prisma.FilamentsWhereInput
  orderBy?: Prisma.FilamentsOrderByWithRelationInput | Prisma.FilamentsOrderByWithRelationInput[]
  cursor?: Prisma.FilamentsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FilamentsScalarFieldEnum | Prisma.FilamentsScalarFieldEnum[]
}

/**
 * Materials without action
 */
export type MaterialsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Materials
   */
  select?: Prisma.MaterialsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Materials
   */
  omit?: Prisma.MaterialsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaterialsInclude<ExtArgs> | null
}
