#Usa como base la imagen oficial de Node.js
FROM node:24 AS development
ENV NODE_ENV development

WORKDIR /cache
COPY package.json .
COPY package-lock.json .
RUN npm i

WORKDIR /app
COPY . .
EXPOSE 3000


